#if !canImport(ObjectiveC)
import XCTest

extension K8sServiceDiscoveryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__K8sServiceDiscoveryTests = [
        ("testFixedListImpl", testFixedListImpl),
        ("testOneShotLookup", testOneShotLookup),
        ("testSubscription", testSubscription),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(K8sServiceDiscoveryTests.__allTests__K8sServiceDiscoveryTests),
    ]
}
#endif
